### ISSUE TITLE
[データ準備] これまでの本(Book)、直近3回ぐらいの活動(Activity)のデータ準備

### ISSUE THREAD

**Issue by shakemurasan** [muramurasan/dsoft#28]
以下について、以下のスプレッドシートにまとめていって欲しいです。
スプレッドシートの内容をもとに、 @muramurasan がDBにデータ流し込みます。

https://docs.google.com/spreadsheets/d/1bc63_UKvDac-UuV6KG_2diDtniqZec92AGs98Fp7o7I/edit?usp=sharing
(いつまでも公開すべき情報じゃないので、初期データ投入終えたら非公開にするか消します)

画像は、最終的に @muramurasan が建てようと思う、AWSのS3にアップロードして使います。

# Book
- 本のタイトル
- 本の説明
- 本の画像へのpath
  - 画像ファイル直貼りでもいいです

# Activity
- 第xx回の活動か
    - 第xx回に分類されなければ、何の活動名か？(例：秋のLT大会)
- 活動した内容の説明(簡単でいいです)
- 活動の様子の写真へのpath
  - 画像ファイル直貼りでもいいです
  - なかったらなかったでいいです

**Comment by uphy** [comment]
Book、説明はAmazon 等から抜粋でとりあえず作成しました！
ちょっとかじったのも合わせると結構いろいろ読んでる！
他に足りないの思い当たったら追記お願いしまーす！

**Comment by uphy** [comment]
最近の活動、あんまり勉強会らしくなくて書けたもんじゃないな・・・

**Comment by uphy** [comment]
過去3回書きました！
それ以上は覚えてない！記録もあまり残ってない！
今後の勉強会は毎回一言書いて、写真を撮りたい

**Comment by shakemurasan** [comment]
チェックしました。僕はOKだと思います！
(もりもりデータ準備してくれてありがとう！)

よきタイミングでissue閉じておいてくださいー
