### ISSUE TITLE
タイトルが2行になるとレイアウト崩れるので修正して欲しい

### ISSUE THREAD

**Issue by shakemurasan** [muramurasan/dsoft#43]
こんな感じで、2行にタイトルがなると、なんか崩れる。辛い。
![2017-07-27 16 53 24](https://user-images.githubusercontent.com/14919586/28659988-4440bdc0-72ec-11e7-88c1-6a18e373a42c.png)

**Comment by uphy** [comment]
正直まあ悪くないかなーと思う！ｗ

**Comment by uphy** [comment]
単語単位とかでinline-blockな要素で区切って、line-height広げてやると、いい感じに表示できそうね

**Comment by uphy** [comment]
こんな感じに区切るようにしたよ！
<img width="718" alt="2017-09-02 15 17 59" src="https://user-images.githubusercontent.com/1233373/29993443-0a14ed6a-8ff2-11e7-8a26-01ead22c1056.png">
