### ISSUE TITLE
現在登録されているBookにCategoryを紐付ける(seedの準備)

### ISSUE THREAD

**Issue by shakemurasan** [muramurasan/dsoft#71]
後、どなたかカテゴリの対応表埋めていただけると、自分がそれにならってデータ流し込みます。

|本の名前|カテゴリー|
|---|---|
|サイバーセキュリティプログラミング ―― Pythonで学ぶハッカーの思考||
|マイクロサービスアーキテクチャ||
|プログラマ脳を鍛える数学パズル シンプルで高速なコードが書けるようになる70問|algorithm, programming|
|インタフェースデザインの心理学||
|レガシーコード改善ガイド	保守開発のためのリファクタリング！||
|パターン指向リファクタリング入門~ソフトウエア設計を改善する27の作法||
|Java言語で学ぶデザインパターン入門||
|Head Firstデザインパターン ―頭とからだで覚えるデザインパターン||

**Comment by uphy** [comment]
こんな感じ？
https://docs.google.com/spreadsheets/d/1bc63_UKvDac-UuV6KG_2diDtniqZec92AGs98Fp7o7I/edit?usp=sharing

今更気づいたけど、今やってる本入ってないねｗ
そのうち追加します！

**Comment by shakemurasan** [comment]
ありがたやー。やっておきまーす

**Comment by shakemurasan** [comment]
やったお。
ついでに、数学パズルもうやっていないと思うから、今やっている本からは外しておきますた
